# Generated by Django 5.0.6 on 2024-07-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='User_id',
            new_name='login_id',
        ),
    ]
