# Generated by Django 5.0.6 on 2024-08-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turfowner',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
