# Generated by Django 5.0.6 on 2024-07-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0002_rename_user_id_user_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
