# Generated by Django 5.0.6 on 2024-07-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0003_loginuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
