# Generated by Django 5.0.6 on 2024-07-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0004_loginuser_date_of_birth_loginuser_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='turf_id',
            new_name='turf_name',
        ),
    ]
