# Generated by Django 5.0.6 on 2024-07-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0005_rename_turf_id_turf_turf_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='turf_name',
            new_name='turf_id',
        ),
    ]
