# Generated by Django 5.0.6 on 2024-07-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0006_rename_turf_name_turf_turf_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='turf_id',
            new_name='turf_name',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='turf_features',
        ),
    ]
