# Generated by Django 5.0.6 on 2024-07-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0007_rename_turf_id_turf_turf_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='turf_name',
            field=models.CharField(max_length=100),
        ),
    ]
