# Generated by Django 5.0.6 on 2024-07-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0008_alter_turf_turf_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='turfowner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='turf',
            name='turf_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turfindapp.turfowner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turfowner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turfowner',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
