# Generated by Django 5.0.6 on 2024-07-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0009_remove_loginuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='turf_id',
        ),
        migrations.RemoveField(
            model_name='turfowner',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='turfowner',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='turfowner',
            name='password',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
