# Generated by Django 5.0.6 on 2024-07-14 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0010_remove_turf_turf_id_remove_turfowner_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='turf_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='turfindapp.turfowner'),
            preserve_default=False,
        ),
    ]
