# Generated by Django 5.0.6 on 2024-07-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0011_turf_turf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='turf_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turfindapp.turfowner'),
        ),
    ]
