# Generated by Django 5.0.6 on 2024-07-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0012_alter_turf_turf_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='gender',
        ),
    ]
