# Generated by Django 5.0.6 on 2024-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0014_turfowner_date_of_birth_turfowner_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='category',
            field=models.CharField(choices=[('iconic', 'Iconic Stadiums'), ('economical', 'Economical Grass Choices'), ('eleven_a_side', '11-a-side Turf'), ('newly_added', 'Newly Added Turfs')], default='newly_added', max_length=20),
        ),
    ]
