# Generated by Django 5.0.6 on 2024-07-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0015_turf_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='login_user',
            new_name='login_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='login_id',
        ),
    ]
