# Generated by Django 5.0.6 on 2024-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfindapp', '0017_remove_booking_booking_id_remove_review_review_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
